# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Work\Python\KeyDataSearch-Python\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 392)
        self.pushButton_selectOutput = QtWidgets.QPushButton(MainWindow)
        self.pushButton_selectOutput.setGeometry(QtCore.QRect(70, 130, 201, 23))
        self.pushButton_selectOutput.setObjectName("pushButton_selectOutput")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(70, 200, 201, 81))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(0)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.go = QtWidgets.QPushButton(MainWindow)
        self.go.setGeometry(QtCore.QRect(410, 320, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.go.setFont(font)
        self.go.setObjectName("go")
        self.lineEdit_outPutPath = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_outPutPath.setGeometry(QtCore.QRect(300, 130, 331, 20))
        self.lineEdit_outPutPath.setObjectName("lineEdit_outPutPath")
        self.lineEdit_resPath = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_resPath.setGeometry(QtCore.QRect(300, 70, 331, 20))
        self.lineEdit_resPath.setObjectName("lineEdit_resPath")
        self.pushButton_selectResFolder = QtWidgets.QPushButton(MainWindow)
        self.pushButton_selectResFolder.setGeometry(QtCore.QRect(70, 70, 201, 23))
        self.pushButton_selectResFolder.setObjectName("pushButton_selectResFolder")
        self.textEdit_keys = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_keys.setGeometry(QtCore.QRect(300, 190, 331, 101))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit_keys.setFont(font)
        self.textEdit_keys.setObjectName("textEdit_keys")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 211, 51))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(0)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.textEdit_inputFileKeys = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_inputFileKeys.setGeometry(QtCore.QRect(300, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit_inputFileKeys.setFont(font)
        self.textEdit_inputFileKeys.setObjectName("textEdit_inputFileKeys")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抓取关键字小工具"))
        self.pushButton_selectOutput.setText(_translate("MainWindow", "选择要生成的文件路径"))
        self.label.setText(_translate("MainWindow", "输入需要抓取的关键字（每个关键字用#号隔开）"))
        self.go.setText(_translate("MainWindow", "Go"))
        self.pushButton_selectResFolder.setText(_translate("MainWindow", "选择要抓取的源文件夹"))
        self.label_2.setText(_translate("MainWindow", "需要遍历的文件名的关键字(以#号隔开)"))
