# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Work\Python\KeyDataSearch-Python\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 379)
        self.pushButton_selectOutput = QtWidgets.QPushButton(MainWindow)
        self.pushButton_selectOutput.setGeometry(QtCore.QRect(70, 110, 131, 23))
        self.pushButton_selectOutput.setObjectName("pushButton_selectOutput")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(70, 180, 151, 51))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(0)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.go = QtWidgets.QPushButton(MainWindow)
        self.go.setGeometry(QtCore.QRect(340, 300, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.go.setFont(font)
        self.go.setObjectName("go")
        self.lineEdit_outPutPath = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_outPutPath.setGeometry(QtCore.QRect(230, 110, 331, 20))
        self.lineEdit_outPutPath.setObjectName("lineEdit_outPutPath")
        self.lineEdit_resPath = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_resPath.setGeometry(QtCore.QRect(230, 50, 331, 20))
        self.lineEdit_resPath.setObjectName("lineEdit_resPath")
        self.pushButton_selectResFolder = QtWidgets.QPushButton(MainWindow)
        self.pushButton_selectResFolder.setGeometry(QtCore.QRect(70, 50, 131, 23))
        self.pushButton_selectResFolder.setObjectName("pushButton_selectResFolder")
        self.textEdit_keys = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_keys.setGeometry(QtCore.QRect(230, 170, 331, 101))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit_keys.setFont(font)
        self.textEdit_keys.setObjectName("textEdit_keys")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抓取关键字小工具"))
        self.pushButton_selectOutput.setText(_translate("MainWindow", "选择要生成的文件路径"))
        self.label.setText(_translate("MainWindow", "输入需要抓取的关键字（每个关键字用#号隔开）"))
        self.go.setText(_translate("MainWindow", "Go"))
        self.pushButton_selectResFolder.setText(_translate("MainWindow", "选择要抓取的源文件夹"))
